---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bootnetic
description: Custom Fedora Kinoite image for ThinkPad T460

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - peterwu/iosevka
        - theblackdon/kineticwe
        - lionheartp/Hyprland
        - theblackdon/dcli-bootc
        - linuxgamerlife/lgl-dnf-helper
        - linuxgamerlife/lgl-emoji-picker

  - type: script
    snippets:
      - "curl -sL https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo -o /etc/yum.repos.d/terra.repo"
      # Swap/override base kwin-common with kineticwe from COPR
      - "rpm-ostree override replace --experimental --from repo='copr:copr.fedorainfracloud.org:theblackdon:kineticwe' kwin-common || dnf swap -y kwin-common kineticwe"

  - type: rpm-ostree
    install:
      - noctalia-git
      - qt5ct
      - qt6ct
      - nwg-look
      - adw-gtk3-theme
      - kitty
      - fish
      - lgl-emoji-picker
      - lgl-dnf-helper
      - iosevka-fonts
      - fastfetch
      - btop
      - htop
      - git
      - zoxide
      - eza
      - gwenview
      - haruna
      - zathura
      - neovim
    remove:
      - firefox
      - firefox-langpacks

  # 3. System-wide Flatpaks (v2 syntax)
  - type: default-flatpaks
    notify: true
    system:
      flatpaks:
        - com.google.Chrome
        - io.github.equibop.Equibop

  # 4. Install Homebrew
  - type: brew

  # 5. Install Nix (via script module)
  - type: script
    snippets:
     - "curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --init none --no-confirm"

  # 6. Custom scripts
  - type: script
    snippets:
      - "sed -i 's|SHELL=/bin/bash|SHELL=/usr/bin/fish|' /etc/default/useradd"
      - "grep -qxF '/usr/bin/fish' /etc/shells || echo '/usr/bin/fish' >> /etc/shells"
      - "echo 'Custom image build finished successfully!'"
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully